/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg2_claudiacortes;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Claudia Cortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearAstrounatas = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_nacionalidad = new javax.swing.JTextField();
        js_sueldo = new javax.swing.JSpinner();
        js_pesoastro = new javax.swing.JSpinner();
        txt_exp = new javax.swing.JTextField();
        jc_Sexo = new javax.swing.JComboBox<>();
        btn_crearastro = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        jd_planeta = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_nombreplaneta = new javax.swing.JTextField();
        js_tempPlaneta = new javax.swing.JSpinner();
        cb_anillo = new javax.swing.JComboBox<>();
        txt_superficie = new javax.swing.JTextField();
        js_distancia = new javax.swing.JSpinner();
        btn_crearplaneta = new javax.swing.JButton();
        btn_modPlaneta = new javax.swing.JButton();
        jd_CrearExpedicion = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jc_naveshilo = new javax.swing.JComboBox<>();
        jc_planetasdestino = new javax.swing.JComboBox<>();
        btn_guardar = new javax.swing.JButton();
        pb_ida = new javax.swing.JProgressBar();
        pb_regreso = new javax.swing.JProgressBar();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jd_Listar = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_astro = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_planetas = new javax.swing.JTable();
        jd_naves = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_Agregarastro = new javax.swing.JButton();
        btn_crearnave = new javax.swing.JButton();
        js_serie = new javax.swing.JSpinner();
        js_velocidad = new javax.swing.JSpinner();
        jc_tiponave = new javax.swing.JComboBox<>();
        txt_material = new javax.swing.JTextField();
        js_peso = new javax.swing.JSpinner();
        txt_despegue = new javax.swing.JTextField();
        jc_astro = new javax.swing.JComboBox<>();
        cb_DestinoNave = new javax.swing.JComboBox<>();
        pp_astro = new javax.swing.JPopupMenu();
        jmi_eliminarastro = new javax.swing.JMenuItem();
        jmi_modificarastro = new javax.swing.JMenuItem();
        pp_planeta = new javax.swing.JPopupMenu();
        jmi_eliminarplane = new javax.swing.JMenuItem();
        jmi_modificarplane = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre");

        jLabel2.setText("Nacionalidad");

        jLabel3.setText("Sueldo");

        jLabel4.setText("Experiencia");

        jLabel5.setText("Sexo");

        jLabel6.setText("Peso (KG)");

        js_sueldo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        js_pesoastro.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jc_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        btn_crearastro.setText("Crear");
        btn_crearastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearastroMouseClicked(evt);
            }
        });

        btn_Modificar.setText("Modificar");
        btn_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearAstrounatasLayout = new javax.swing.GroupLayout(jd_CrearAstrounatas.getContentPane());
        jd_CrearAstrounatas.getContentPane().setLayout(jd_CrearAstrounatasLayout);
        jd_CrearAstrounatasLayout.setHorizontalGroup(
            jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearAstrounatasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(jd_CrearAstrounatasLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(52, 52, 52)))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_nacionalidad)
                        .addComponent(txt_nombre)
                        .addComponent(txt_exp)
                        .addComponent(js_sueldo)
                        .addComponent(jc_Sexo, 0, 143, Short.MAX_VALUE))
                    .addComponent(js_pesoastro, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(jd_CrearAstrounatasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btn_crearastro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Modificar)
                .addGap(72, 72, 72))
        );
        jd_CrearAstrounatasLayout.setVerticalGroup(
            jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearAstrounatasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(js_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jc_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(js_pesoastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_CrearAstrounatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crearastro)
                    .addComponent(btn_Modificar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel7.setText("Nombre");

        jLabel8.setText("Temperatura Media");

        jLabel17.setText("Anillos");

        jLabel18.setText("Superficie");

        jLabel19.setText("Distancia Tierra");

        js_tempPlaneta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        cb_anillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        js_distancia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btn_crearplaneta.setText("Crear");
        btn_crearplaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearplanetaMouseClicked(evt);
            }
        });

        btn_modPlaneta.setText("Modificar");
        btn_modPlaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modPlanetaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_planetaLayout = new javax.swing.GroupLayout(jd_planeta.getContentPane());
        jd_planeta.getContentPane().setLayout(jd_planetaLayout);
        jd_planetaLayout.setHorizontalGroup(
            jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_planetaLayout.createSequentialGroup()
                .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_planetaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jd_planetaLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(cb_anillo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_planetaLayout.createSequentialGroup()
                                .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_planetaLayout.createSequentialGroup()
                                        .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel18))
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_planetaLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(55, 55, 55)))
                                .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombreplaneta)
                                    .addComponent(js_tempPlaneta)
                                    .addComponent(txt_superficie)
                                    .addComponent(js_distancia)))))
                    .addGroup(jd_planetaLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btn_crearplaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btn_modPlaneta)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jd_planetaLayout.setVerticalGroup(
            jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_planetaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nombreplaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(js_tempPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cb_anillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txt_superficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(js_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jd_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modPlaneta)
                    .addComponent(btn_crearplaneta))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jLabel20.setText("Nave");

        jLabel21.setText("Planeta");

        btn_guardar.setText("Empezar");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });

        jLabel22.setText("Tiempo Ida");

        jLabel23.setText("Tiempo Regreso");

        javax.swing.GroupLayout jd_CrearExpedicionLayout = new javax.swing.GroupLayout(jd_CrearExpedicion.getContentPane());
        jd_CrearExpedicion.getContentPane().setLayout(jd_CrearExpedicionLayout);
        jd_CrearExpedicionLayout.setHorizontalGroup(
            jd_CrearExpedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearExpedicionLayout.createSequentialGroup()
                .addGroup(jd_CrearExpedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearExpedicionLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jd_CrearExpedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_CrearExpedicionLayout.createSequentialGroup()
                                .addGroup(jd_CrearExpedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21)
                                .addGroup(jd_CrearExpedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_guardar)
                                    .addGroup(jd_CrearExpedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jc_naveshilo, 0, 188, Short.MAX_VALUE)
                                        .addComponent(jc_planetasdestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(pb_regreso, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(pb_ida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_CrearExpedicionLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel22))
                    .addGroup(jd_CrearExpedicionLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel23)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jd_CrearExpedicionLayout.setVerticalGroup(
            jd_CrearExpedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearExpedicionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jd_CrearExpedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jc_naveshilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_CrearExpedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jc_planetasdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(btn_guardar)
                .addGap(29, 29, 29)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(pb_ida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pb_regreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jt_astro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacionalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_astro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_astroMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_astro);
        if (jt_astro.getColumnModel().getColumnCount() > 0) {
            jt_astro.getColumnModel().getColumn(0).setResizable(false);
            jt_astro.getColumnModel().getColumn(1).setResizable(false);
            jt_astro.getColumnModel().getColumn(2).setResizable(false);
            jt_astro.getColumnModel().getColumn(3).setResizable(false);
            jt_astro.getColumnModel().getColumn(4).setResizable(false);
            jt_astro.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Astronautas", jPanel1);

        jt_planetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Temperatura", "Anillos", "Superficie", "Distancia"
            }
        ));
        jt_planetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_planetasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_planetas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Planetas", jPanel2);

        javax.swing.GroupLayout jd_ListarLayout = new javax.swing.GroupLayout(jd_Listar.getContentPane());
        jd_Listar.getContentPane().setLayout(jd_ListarLayout);
        jd_ListarLayout.setHorizontalGroup(
            jd_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jd_ListarLayout.setVerticalGroup(
            jd_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel9.setText("Serie");

        jLabel10.setText("Destino");

        jLabel11.setText("Velocidad");

        jLabel12.setText("Tipo de Nave");

        jLabel13.setText("Material");

        jLabel14.setText("Peso");

        jLabel15.setText("Lugar Despegue");

        jLabel16.setText("Astrounaturas");

        btn_Agregarastro.setText("Agregar");
        btn_Agregarastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgregarastroMouseClicked(evt);
            }
        });

        btn_crearnave.setText("Crear");
        btn_crearnave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearnaveMouseClicked(evt);
            }
        });

        js_serie.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        js_velocidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jc_tiponave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----Seleccione------", "Tripulada", "Sonda espacial" }));

        txt_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_materialMouseClicked(evt);
            }
        });

        js_peso.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jd_navesLayout = new javax.swing.GroupLayout(jd_naves.getContentPane());
        jd_naves.getContentPane().setLayout(jd_navesLayout);
        jd_navesLayout.setHorizontalGroup(
            jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_navesLayout.createSequentialGroup()
                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_navesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_navesLayout.createSequentialGroup()
                                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(31, 31, 31)
                                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jc_tiponave, 0, 176, Short.MAX_VALUE)
                                    .addComponent(js_serie)
                                    .addComponent(js_velocidad)
                                    .addComponent(txt_material)
                                    .addComponent(js_peso)
                                    .addComponent(cb_DestinoNave, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jd_navesLayout.createSequentialGroup()
                                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_despegue)
                                    .addComponent(jc_astro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_navesLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btn_crearnave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_Agregarastro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jd_navesLayout.setVerticalGroup(
            jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_navesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(js_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_DestinoNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(js_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jc_tiponave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(js_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_despegue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btn_Agregarastro)
                    .addComponent(jc_astro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btn_crearnave)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jmi_eliminarastro.setText("Eliminar Astronauta");
        jmi_eliminarastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarastroActionPerformed(evt);
            }
        });
        pp_astro.add(jmi_eliminarastro);

        jmi_modificarastro.setText("Modificar Astronauta");
        jmi_modificarastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarastroActionPerformed(evt);
            }
        });
        pp_astro.add(jmi_modificarastro);

        jmi_eliminarplane.setText("Eliminar Planeta");
        jmi_eliminarplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarplaneActionPerformed(evt);
            }
        });
        pp_planeta.add(jmi_eliminarplane);

        jmi_modificarplane.setText("Modificar Planeta");
        jmi_modificarplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarplaneActionPerformed(evt);
            }
        });
        pp_planeta.add(jmi_modificarplane);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Nuevo");

        jMenuItem1.setText("Astrounatas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Naves");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Expedicion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Planetas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Archivo");

        jMenuItem5.setText("Listar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jd_naves.show();
        jd_naves.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_crearastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearastroMouseClicked
        try {
            int peso = (int) js_pesoastro.getValue();
            String Nacionalidad = txt_nacionalidad.getText();
            double sueldo = (double) js_sueldo.getValue();
            String Experiencia = txt_exp.getText();
            String Sexo = jc_Sexo.getSelectedItem().toString();
            String Nombre = txt_nombre.getText();
            Astrounatas Astro = new Astrounatas();
            Object[] newrow = {
                Nombre, Nacionalidad, sueldo, Experiencia, Sexo, peso
            };
            /*AGREGARLE PROPIEDADES*/
            Astro.setExperiencia(Experiencia);
            Astro.setNacionalidad(Nacionalidad);
            Astro.setNombre(Nombre);
            Astro.setPeso(peso);
            Astro.setSueldo(sueldo);
            Astro.setSexo(Sexo);
            /*Agregando la fila*/
            DefaultTableModel Modelo = (DefaultTableModel) jt_astro.getModel();
            Modelo.addRow(newrow);
            jt_astro.setModel(Modelo);

            DefaultComboBoxModel modeloastros = (DefaultComboBoxModel) jc_astro.getModel();
            modeloastros.addElement(Astro);
            Astros.add(Astro);
            JOptionPane.showMessageDialog(jd_CrearAstrounatas, "Creado Exitosamente");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_crearastroMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jd_CrearAstrounatas.show();
        jd_CrearAstrounatas.setLocationRelativeTo(this);
        btn_Modificar.setVisible(false);
        btn_crearastro.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jd_CrearExpedicion.show();
        jd_CrearExpedicion.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jd_planeta.show();
        jd_planeta.setLocationRelativeTo(this);
        btn_modPlaneta.show(false);
        btn_crearplaneta.show(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jd_Listar.show();
        jd_Listar.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btn_crearplanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearplanetaMouseClicked
        try {
            String Nombre = txt_nombreplaneta.getText();
            int Temp = (int) js_tempPlaneta.getValue();
            String Anillo = cb_anillo.getSelectedItem().toString();
            String Superficie = txt_superficie.getText();
            int Distancia = (int) js_distancia.getValue();
            Planetas Plane = new Planetas();
            Object[] newrow = {Nombre, Temp, Anillo, Superficie, Distancia
            };
            /*AGREGARLE PROPIEDADES*/
            Plane.setAnillos(Anillo);
            Plane.setDistancia_Tierra(Distancia);
            Plane.setNombre(Nombre);
            Plane.setTemperatura(Temp);
            Plane.setTipo_superficie(Superficie);
            /*Agregando la fila*/
            DefaultTableModel Modelo = (DefaultTableModel) jt_planetas.getModel();
            Modelo.addRow(newrow);
            jt_planetas.setModel(Modelo);
            
            DefaultComboBoxModel modeloplane = (DefaultComboBoxModel) jc_planetasdestino.getModel();
            modeloplane.addElement(Plane);
            Planetas.add(Plane);
            cb_DestinoNave.setModel(modeloplane);
            jc_planetasdestino.setModel(modeloplane);
            JOptionPane.showMessageDialog(jd_CrearAstrounatas, "Creado Exitosamente");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_crearplanetaMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
//        try {
           
//            JOptionPane.showMessageDialog(jd_CrearExpedicion, "Expedicion creada");
//            /*RECORDAR PONER EL HILO*/
////            Hilo_Expedicion Hilo=new  Hilo_Expedicion(pb_ida,pb_regreso);
//        } catch (Exception e) {
//
//        }
        try {
            // expedicion.setAvanzar(false);

            Naves Nave = ((Naves) jc_naveshilo.getSelectedItem());
            Planetas Destino = ((Planetas) jc_planetasdestino.getSelectedItem());
            Hilo_Expedicion Expedicion = new Hilo_Expedicion(Nave, Destino, pb_ida, pb_regreso);
            double ida = 0;
            double regreso = 0;
            double[] Tiempo = Nave.CalcularTiempo();
            ida = Tiempo[0]*1000;
            regreso = Tiempo[1]*1000;
//            if (Nave instanceof SondaEspacial) {
//                ida = (( (SondaEspacial)nave).polimorfo()[0] * 1000);
//                regreso = (( (SondaEspacial)nave).polimorfo()[1] * 1000);
//            }else if(nave instanceof Tripulada){
//                ida = (( (Tripulada)nave).polimorfo()[0] * 1000);
//                regreso = (( (Tripulada)nave).polimorfo()[1] * 1000);
//            }
            pb_ida.setValue(0);
            pb_regreso.setValue(0);
            pb_ida.setMaximum((int)ida);
            pb_regreso.setMaximum((int)regreso);
            System.out.println("TIEMPO DE IDA " + ida);
            System.out.println("TIMEPO DE REGRESO" + regreso);
            Expedicion.start();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_guardarMouseClicked

    private void jmi_eliminarplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarplaneActionPerformed
        if (jt_planetas.getSelectedRow() >= 0) {
            try {
                DefaultTableModel Modelo = (DefaultTableModel) jt_planetas.getModel();
                Modelo.removeRow(jt_planetas.getSelectedRow());
                jt_planetas.setModel(Modelo);
                Planetas.remove(jt_planetas.getSelectedRow());
                JOptionPane.showMessageDialog(jd_Listar, "Se ha eliminado el elemento");
                Actualizar_Plane();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_jmi_eliminarplaneActionPerformed

    private void jt_planetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_planetasMouseClicked
        if (evt.isMetaDown() && jt_planetas.getSelectedRow() >= 0) {
            pp_planeta.show(evt.getComponent(), evt.getX(), evt.getY());
            Actual_planeta = Planetas.get(jt_planetas.getSelectedRow());

        }
    }//GEN-LAST:event_jt_planetasMouseClicked

    private void jmi_eliminarastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarastroActionPerformed
        if (jt_astro.getSelectedRow() >= 0) {
            try {
                DefaultTableModel Modelo = (DefaultTableModel) jt_astro.getModel();
                Modelo.removeRow(jt_astro.getSelectedRow());
                jt_astro.setModel(Modelo);
                Astros.remove(jt_astro.getSelectedRow());
                Actualizar();
                JOptionPane.showMessageDialog(jd_Listar, "Se ha eliminado el elemento");
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_jmi_eliminarastroActionPerformed

    private void jt_astroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_astroMouseClicked
        if (evt.isMetaDown() && jt_astro.getSelectedRow() >= 0) {
            pp_astro.show(evt.getComponent(), evt.getX(), evt.getY());
            Actual_astro = Astros.get(jt_astro.getSelectedRow());
        }
    }//GEN-LAST:event_jt_astroMouseClicked

    private void jmi_modificarplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarplaneActionPerformed
        try {
            if (Actual_planeta != null) {
                txt_nombreplaneta.setText(Actual_planeta.getNombre());
                js_tempPlaneta.setValue(Actual_planeta.getTemperatura());
                cb_anillo.setSelectedItem(Actual_planeta.isAnillos());
                txt_superficie.setText(Actual_planeta.getTipo_superficie());
                js_distancia.setValue(Actual_planeta.getDistancia_Tierra());
                btn_modPlaneta.show(true);
                btn_crearplaneta.show(false);
                jd_planeta.show();
                jd_planeta.setLocationRelativeTo(this);

            }

        } catch (Exception E) {

        }
    }//GEN-LAST:event_jmi_modificarplaneActionPerformed

    private void jmi_modificarastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarastroActionPerformed
        if (Actual_astro != null) {
            try {
                js_pesoastro.setValue(Actual_astro.getPeso());
                txt_nacionalidad.setText(Actual_astro.getNacionalidad());
                js_sueldo.setValue(Actual_astro.getSueldo());
                txt_exp.setText(Actual_astro.getExperiencia());
                jc_Sexo.setSelectedItem(Actual_astro.getSexo());
                txt_nombre.setText(Actual_astro.getNombre());
                jd_CrearAstrounatas.show();
                jd_CrearAstrounatas.setLocationRelativeTo(this);
                btn_Modificar.setVisible(true);
                btn_crearastro.setVisible(false);
                //  Actualizar();

            } catch (Exception e) {

            }

        }
    }//GEN-LAST:event_jmi_modificarastroActionPerformed
    public void Actualizar() {
        jt_astro.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Nacioalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
                }
        ) {
        });
        DefaultTableModel Modelo = (DefaultTableModel) jt_astro.getModel();
        DefaultComboBoxModel modeloastros = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloplane = new DefaultComboBoxModel();

        for (Astrounatas Astro : Astros) {
            Object[] newrow = {Astro.getNombre(), Astro.getNacionalidad(), Astro.getSueldo(), Astro.getExperiencia(), Astro.getSexo(), Astro.getPeso()
            };
            modeloplane.addElement(Astro);
            Modelo.addRow(newrow);
        }
        jt_astro.setModel(Modelo);
        jc_astro.setModel(modeloplane);
        JOptionPane.showMessageDialog(jd_Listar, "Se ha Modificado el Astronauta");
    }

    public void Actualizar_Plane() {
        /*LA TABLA RESETEAMOS LA TABLA*/
        jt_planetas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Temperatura", "Anillos", "Superficie", "Distancia"
                }
        ) {

        });

        DefaultTableModel Modelo = (DefaultTableModel) jt_planetas.getModel();
        DefaultComboBoxModel modeloplane = new DefaultComboBoxModel();

        for (Planetas Planeta : Planetas) {
            Object[] newrow = {Planeta.getNombre(), Planeta.getTemperatura(), Planeta.isAnillos(), Planeta.getTipo_superficie(), Planeta.getDistancia_Tierra()
            };
            modeloplane.addElement(Planeta);
            Modelo.addRow(newrow);

        }
        jc_planetasdestino.setModel(modeloplane);
        jt_planetas.setModel(Modelo);
        cb_DestinoNave.setModel(modeloplane);/*AGREGUE ESTO Y SI FALLA FUE CULPA DE ESTO*/
        JOptionPane.showMessageDialog(jd_Listar, "Se ha Modificado el planeta");
    }
    private void btn_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModificarMouseClicked
        int peso = (int) js_pesoastro.getValue();
        String Nacionalidad = txt_nacionalidad.getText();
        double sueldo = (double) js_sueldo.getValue();
        String Experiencia = txt_exp.getText();
        String Sexo = jc_Sexo.getSelectedItem().toString();
        String Nombre = txt_nombre.getText();
        Astrounatas Astro = new Astrounatas();

        /*AGREGARLE PROPIEDADES*/
        Actual_astro.setExperiencia(Experiencia);
        Actual_astro.setNacionalidad(Nacionalidad);
        Actual_astro.setNombre(Nombre);
        Actual_astro.setPeso(peso);
        Actual_astro.setSueldo(sueldo);
        Actual_astro.setSexo(Sexo);
        /*Agregando la fila*/
        Actualizar();
    }//GEN-LAST:event_btn_ModificarMouseClicked

    private void btn_modPlanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modPlanetaMouseClicked
        String Nombre = txt_nombreplaneta.getText();
        int Temp = (int) js_tempPlaneta.getValue();
        String Anillo = cb_anillo.getSelectedItem().toString();
        String Superficie = txt_superficie.getText();
        int Distancia = (int) js_distancia.getValue();
        Actual_planeta.setAnillos(Anillo);
        Actual_planeta.setDistancia_Tierra(Distancia);
        Actual_planeta.setNombre(Nombre);
        Actual_planeta.setTemperatura(Temp);
        Actual_planeta.setTipo_superficie(Superficie);
        Actualizar_Plane();

    }//GEN-LAST:event_btn_modPlanetaMouseClicked

    private void txt_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_materialMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_materialMouseClicked

    private void btn_AgregarastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarastroMouseClicked
        Astrounatas Tripulante = (Astrounatas) jc_astro.getSelectedItem();
        if (Tripulantes.contains(Tripulante)) {
            JOptionPane.showMessageDialog(null, "El astronauta ya se encuentra en la expedicion");
        } else {
            Tripulantes.add(Tripulante);
        }
    }//GEN-LAST:event_btn_AgregarastroMouseClicked

    private void btn_crearnaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearnaveMouseClicked
        int Serie = (int) js_serie.getValue();
        Planetas Destino = (Planetas) cb_DestinoNave.getSelectedItem();
        int Velocidad = (int) js_velocidad.getValue();
        int Tipo = jc_tiponave.getSelectedIndex();
        String Material = txt_material.getText();
        int Peso = (int) js_peso.getValue();
        /*-----Seleccione------
Tripulada
Sonda espacial*/
        if (Tipo == 1) {//Tripulada
            Nave_Tripulada NT = new Nave_Tripulada();
            NT.setDestino(Destino);
            NT.setNum_Serie(Serie);
            NT.setVelocidad(Velocidad);
            NT.setLugar_Despegue(txt_despegue.getText());
            NT.setTripulantes(Tripulantes);
            DefaultComboBoxModel Modelo=(DefaultComboBoxModel)jc_naveshilo.getModel();
            Modelo.addElement(NT);
            jc_naveshilo.setModel(Modelo);
            JOptionPane.showMessageDialog(null, "Se creo nave Tripulada");
        } else if (Tipo == 2) {//Sonda
            Sonda_Espacial SE = new Sonda_Espacial();
            SE.setDestino(Destino);
            SE.setMaterial(Material);
            SE.setNum_Serie(Serie);
            SE.setVelocidad(Velocidad);
              DefaultComboBoxModel Modelo=(DefaultComboBoxModel)jc_naveshilo.getModel();
            Modelo.addElement(SE);
            jc_naveshilo.setModel(Modelo);
            JOptionPane.showMessageDialog(null, "Se creo Sonda Espacial");

        }
    }//GEN-LAST:event_btn_crearnaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregarastro;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_crearastro;
    private javax.swing.JButton btn_crearnave;
    private javax.swing.JButton btn_crearplaneta;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modPlaneta;
    private javax.swing.JComboBox<String> cb_DestinoNave;
    private javax.swing.JComboBox<String> cb_anillo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jc_Sexo;
    private javax.swing.JComboBox<String> jc_astro;
    private javax.swing.JComboBox<String> jc_naveshilo;
    private javax.swing.JComboBox<String> jc_planetasdestino;
    private javax.swing.JComboBox<String> jc_tiponave;
    private javax.swing.JDialog jd_CrearAstrounatas;
    private javax.swing.JDialog jd_CrearExpedicion;
    private javax.swing.JDialog jd_Listar;
    private javax.swing.JDialog jd_naves;
    private javax.swing.JDialog jd_planeta;
    private javax.swing.JMenuItem jmi_eliminarastro;
    private javax.swing.JMenuItem jmi_eliminarplane;
    private javax.swing.JMenuItem jmi_modificarastro;
    private javax.swing.JMenuItem jmi_modificarplane;
    private javax.swing.JSpinner js_distancia;
    private javax.swing.JSpinner js_peso;
    private javax.swing.JSpinner js_pesoastro;
    private javax.swing.JSpinner js_serie;
    private javax.swing.JSpinner js_sueldo;
    private javax.swing.JSpinner js_tempPlaneta;
    private javax.swing.JSpinner js_velocidad;
    private javax.swing.JTable jt_astro;
    private javax.swing.JTable jt_planetas;
    private javax.swing.JProgressBar pb_ida;
    private javax.swing.JProgressBar pb_regreso;
    private javax.swing.JPopupMenu pp_astro;
    private javax.swing.JPopupMenu pp_planeta;
    private javax.swing.JTextField txt_despegue;
    private javax.swing.JTextField txt_exp;
    private javax.swing.JTextField txt_material;
    private javax.swing.JTextField txt_nacionalidad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreplaneta;
    private javax.swing.JTextField txt_superficie;
    // End of variables declaration//GEN-END:variables
Astrounatas Actual_astro;
    Planetas Actual_planeta;
    ArrayList<Astrounatas> Astros = new ArrayList();
    ArrayList<Planetas> Planetas = new ArrayList();
    ArrayList<Astrounatas> Tripulantes = new ArrayList();
}
